@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level01.bin tiles.png -o level01.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level02.bin tiles.png -o level02.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level03.bin tiles.png -o level03.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level04.bin tiles.png -o level04.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level05.bin tiles.png -o level05.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level06.bin tiles.png -o level06.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level07.bin tiles.png -o level07.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level08.bin tiles.png -o level08.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level09.bin tiles.png -o level09.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level10.bin tiles.png -o level10.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level11.bin tiles.png -o level11.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level12.bin tiles.png -o level12.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level13.bin tiles.png -o level13.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level14.bin tiles.png -o level14.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level15.bin tiles.png -o level15.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level16.bin tiles.png -o level16.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level17.bin tiles.png -o level17.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level18.bin tiles.png -o level18.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level19.bin tiles.png -o level19.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level20.bin tiles.png -o level20.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level21.bin tiles.png -o level21.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level22.bin tiles.png -o level22.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level23.bin tiles.png -o level23.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level24.bin tiles.png -o level24.png
@python ..\..\tools\level2png\level2png.py C:\gb\development\GLUF\res\data\level25.bin tiles.png -o level25.png
