LEVEL2PNG = python ..\..\tools\level2png\level2png.py

all:
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level01.bin tiles1.png -o level01.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level02.bin tiles1.png -o level02.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level03.bin tiles1.png -o level03.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level04.bin tiles1.png -o level04.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level05.bin tiles1.png -o level05.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level06.bin tiles1.png -o level06.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level07.bin tiles1.png -o level07.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level08.bin tiles1.png -o level08.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level09.bin tiles2.png -o level09.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level10.bin tiles2.png -o level10.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level11.bin tiles2.png -o level11.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level12.bin tiles2.png -o level12.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level13.bin tiles2.png -o level13.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level14.bin tiles2.png -o level14.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level15.bin tiles3.png -o level15.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level16.bin tiles3.png -o level16.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level17.bin tiles3.png -o level17.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level18.bin tiles3.png -o level18.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level19.bin tiles3.png -o level19.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level20.bin tiles3.png -o level20.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level21.bin tiles4.png -o level21.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level22.bin tiles4.png -o level22.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level23.bin tiles4.png -o level23.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level24.bin tiles4.png -o level24.png
	$(LEVEL2PNG) C:\gb\development\GLUF\res\data\level25.bin tiles4.png -o level25.png
