#ifndef __INCLUDE_LEVELS_H__
#define __INCLUDE_LEVELS_H__

#define LEVEL_HEIGHT 20
#define LEVEL_WIDTH  12
#define LEVEL_METATILE_HEIGHT 2
#define LEVEL_METATILE_WIDTH  2

#define TILE_BUFFER_WIDTH  32
#define TILE_BUFFER_HEIGHT (LEVEL_HEIGHT * LEVEL_METATILE_HEIGHT)
#define TILE_BUFFER_OFFSET ((TILE_BUFFER_WIDTH - ((LEVEL_WIDTH * LEVEL_METATILE_WIDTH))) >> 1)

#define MOVE_SPEED 1
#define FALL_SPEED 2
#define LIFT_SPEED 2

#define TILE_EMPTY           0
#define TILE_START_POINT     4
#define TILE_END_POINT       40

#define TILE_DOOR            9

#define TILE_LIFT_NONE       TILE_EMPTY
#define TILE_LIFT_UP         5
#define TILE_LIFT_DOWN       10
#define TILE_LIFT_STOP       40

#define TILE_DISAPPEARING    12
#define TILE_DISAPPEARED     3

#define TILE_BATT_CHARGER    11
#define TILE_BATT_DISCHARGED 14
#define TILE_BATT_CHARGED    15

#define ENEMY_UFO_RIGHT      0x21
#define ENEMY_UFO_LEFT       0x22
#define ENEMY_UFO_UP         0x26
#define ENEMY_UFO_DOWN       0x27

#define MOVE_LEFT            0x10
#define MOVE_RIGHT           0x11
#define MOVE_DOWN            0x12
#define MOVE_UP              0x13
#define MOVE_RIGHT_OR_UP     0x14
#define MOVE_LEFT_OR_UP      0x15
#define MOVE_RIGHT_OR_DOWN   0x16
#define MOVE_LEFT_OR_DOWN    0x17

typedef enum enemy_dir_e {
	DIR_NONE = 0,
	DIR_UP,
	DIR_DOWN,
	DIR_LEFT,
	DIR_RIGHT,
	N_DIRECTIONS
} enemy_dir_e;

#define TILE_FIRST_SOLID     TILE_LIFT_DOWN
#define TILE_LAST_VISIBLE    TILE_BATT_CHARGED

extern UINT8 level_buffer[LEVEL_HEIGHT][LEVEL_WIDTH];

#define EXTERN_DATA(A) BANKREF_EXTERN(A)\
extern void A;

EXTERN_DATA(level01)
EXTERN_DATA(level02)
EXTERN_DATA(level03)
EXTERN_DATA(level04)
EXTERN_DATA(level05)
EXTERN_DATA(level06)
EXTERN_DATA(level07)
EXTERN_DATA(level08)
EXTERN_DATA(level09)
EXTERN_DATA(level10)
EXTERN_DATA(level11)
EXTERN_DATA(level12)
EXTERN_DATA(level13)
EXTERN_DATA(level14)
EXTERN_DATA(level15)
EXTERN_DATA(level16)
EXTERN_DATA(level17)
EXTERN_DATA(level18)
EXTERN_DATA(level19)
EXTERN_DATA(level20)
EXTERN_DATA(level21)
EXTERN_DATA(level22)
EXTERN_DATA(level23)
EXTERN_DATA(level24)
EXTERN_DATA(level25)

#endif