#ifndef __INCLUDE_LEVELS_H__
#define __INCLUDE_LEVELS_H__

#include <gbdk/incbin.h>

#define LEVEL_HEIGHT 20
#define LEVEL_WIDTH  12
#define LEVEL_METATILE_HEIGHT 2
#define LEVEL_METATILE_WIDTH  2

extern UINT8 level_buffer[LEVEL_HEIGHT][LEVEL_WIDTH];

INCBIN_EXTERN(level01)
INCBIN_EXTERN(level02)
INCBIN_EXTERN(level03)
INCBIN_EXTERN(level04)
INCBIN_EXTERN(level05)
INCBIN_EXTERN(level06)
INCBIN_EXTERN(level07)
INCBIN_EXTERN(level08)
INCBIN_EXTERN(level09)
INCBIN_EXTERN(level10)
INCBIN_EXTERN(level11)
INCBIN_EXTERN(level12)
INCBIN_EXTERN(level13)
INCBIN_EXTERN(level14)
INCBIN_EXTERN(level15)
INCBIN_EXTERN(level16)
INCBIN_EXTERN(level17)
INCBIN_EXTERN(level18)
INCBIN_EXTERN(level19)
INCBIN_EXTERN(level20)
INCBIN_EXTERN(level21)
INCBIN_EXTERN(level22)
INCBIN_EXTERN(level23)
INCBIN_EXTERN(level24)
INCBIN_EXTERN(level25)

#endif